name: Update Data Dragon Assets

on:
  schedule:
    # Daily 9 PM UTC
    - cron: "0 21 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  updateDdragonAssets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run Script to download & extract the required assets
        working-directory: app
        run: |
          chmod +x ../scripts/getDdragonAssets.sh
          ../scripts/getDdragonAssets.sh

      - name: Commit & Push if Changed
        working-directory: app
        shell: bash
        run: |
          set -euo pipefail

          git config user.name "[Job] ddragon-updater"
          git config user.email "ddragon-updater@users.noreply.github.com"

          git add src/assets/ddragon

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          currentVersion="$(cat src/assets/ddragon/version.txt || true)"
          git commit -m "[DDragon-Update] Update Data Dragon assets to ${currentVersion}"
          git push origin HEAD:main